apiVersion: v1
kind: Service
metadata:
  name: localiza-backend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
    - name: https
      port: 5001
  selector:
    app: localiza-backend
