apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-server
      tier: db
  template:
    metadata:
      labels:
        app: mssql-server
        tier: db
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2017-latest
        name: mssql-server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: localiza-backend-conf
              key: DB_PASSWORD
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-persistent-volume-claim
